# Configure Netlify builds.
[build]
  publish = "dist/"
  command = "npm run build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Commenting out the next line so my posts can be shared anywhere online
    #Content-Security-Policy = "frame-ancestors https://www.linkedin.com"

    # Multi-value headers are expressed with multi-line strings.
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''

# Request bots not to index the admin section.
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/admin/*"

  [headers.values]
    X-Robots-Tag = "noindex"

